[package]
name = "itemize"
version = "0.3.0"
compiler = "0.15.1"
repository = "https://github.com/tianyi-smile/itemize"
entrypoint = "lib.typ"
authors = ["tianyi-smile"]
license = "MIT"
description = "An easy way to customize enum and list."
keywords = ["enum", "list", "item"]
categories = ["components", "utility"]
exclude = ["asserts/", "tests/", "doc/", "examples/"]
